# Conexão com o Banco de Dados (Container Docker)
spring.application.name=agregador
spring.datasource.url=jdbc:postgresql://localhost:5432/ofertas_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate e Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Token do Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}