# Conexão com o Banco de Dados (Container Docker)
spring.application.name=agregador
spring.datasource.url=jdbc:postgresql://localhost:5432/ofertas_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Hibernate e Flyway
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

# Token do Telegram
telegram.bot.token=${TELEGRAM_BOT_TOKEN}


# Configurações da Shopee
shopee.app-id=${SHOPEE_APP_ID}
shopee.secret=${SHOPEE_SECRET}
shopee.api-base-url=https://open-api.affiliate.shopee.com.br/graphql

# Configurações do Mercado Livre
mercadolivre.oauth.client-id=${ML_CLIENT_ID}
mercadolivre.oauth.client-secret=${ML_CLIENT_SECRET}
mercadolivre.oauth.redirect-uri=https://school-height-glad-leads.trycloudflare.com/api/mercadolivre/oauth/callback

# Configurações do Aliexpress
aliexpress.api.app-key=${ALIEXPRESS_APP_KEY}
aliexpress.api.secret=${ALIEXPRESS_SECRET}
aliexpress.api.tracking-id=${ALIEXPRESS_TRACKING_ID}

# Configurações do Magalu
magalu.partner-id=3440
magalu.promoter-id=5773802

# Scanner delay
scanner.fixed-delay-ms=60000
dispatcher.fixed-delay-ms=60000

logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions=TRACE
logging.level.com.ofertas.agregador=DEBUG